### PR TITLE
created rail website

### PR DESCRIPTION
**Pull request by HarshTiwari1234321**
codepen link --- https://codepen.io/harshtiwari1234321/pen/QWWPRWj
image

### CODE REVIEW

**Comment by dojutsu-user** [comment]
UI is not looking good. I am giving 15 points for it.

**Comment by HarshTiwari1234321** [comment]
Sir can i upgrade it..

**Comment by dojutsu-user** [comment]
No.. it's already merged.

**Comment by HarshTiwari1234321** [comment]
Ok sir..

**Pull request merged**
