### PR TITLE
my portfolio

### PR DESCRIPTION
**Pull request by lav-joshi**

### CODE REVIEW

**Comment by dojutsu-user** [comment]
Please provide the codepen link also.

**Comment by lav-joshi** [comment]
codepne link:
https://codepen.io/lav_joshi1056/pen/PoogeMr

**Comment by dojutsu-user** [comment]
Screenshots does not matches.

Screenshot from 2019-11-23 18-03-28

**Comment by lav-joshi** [comment]
sir this is working 
please review

**Comment by lav-joshi** [comment]
@dojutsu-user 
@Divy123 
sir this is working
please review

**Comment by lav-joshi** [comment]
Screenshot from 2019-11-23 19-13-08
Screenshot from 2019-11-23 19-13-14

**Comment by dojutsu-user** [comment]
UI is not good. I am giving 15 points for this.

**Pull request merged**
