### PR TITLE
html and js are present in same file css in the second one and screen…

### PR DESCRIPTION
**Pull request by genjutsumaster**
…shot

code pen link   https://codepen.io/genjutsumaster/pen/eYYMgdw

### CODE REVIEW

**Comment by rishabhshuklax** [comment]
UI is okay-ish and also not responsive but the functionality is good so if you want you can work on the UI you have time until 12 tomorrow night.

**Comment by genjutsumaster** [comment]
Ok sir i will try to improve the ui actually time was not enough so i was
not able to work on ui and responsivity but now I will try to make it good

**Comment by Divy123** [comment]
Stop using sir/mam on GitHub and please mention the issue number.

**Comment by Divy123** [comment]
Set background to white-smoke instead of your image.

**Comment by rishabhshuklax** [comment]
Kindly resolve the merge conflicts.

**Pull request closed without merging**
