### PR TITLE
calculator

### PR DESCRIPTION
**Pull request by sachin746**
codepen==https://codepen.io/sachin746/pen/OJJvNWX
Annotation 2019-11-05 204842

### CODE REVIEW

**Comment by rishabhshuklax** [comment]
Functionality is good but the UI needs some improvements, you have time until tomorrow 12 in the night try to change UI a bit rest everything looks good to me

**Comment by sachin746** [comment]
What type of improvement

**Comment by rishabhshuklax** [comment]
Maybe make the UI a little minimal, try searching internet for examples.

**Comment by sachin746** [comment]
Done

**Pull request merged**
