### PR TITLE
weatherreport

### PR DESCRIPTION
**Pull request by lav-joshi**
my weather report using API

### CODE REVIEW

**Comment by Divy123** [comment]
Your code is not working as on codepen.

**Comment by lav-joshi** [comment]
yes sir but it is working on local machine as i had sent screenshots.

**Comment by lav-joshi** [comment]
https://codepen.io/lav_joshi1056/pen/vYYaOOa

**Comment by dojutsu-user** [comment]
Weather app not working.

**Comment by lav-joshi** [comment]
@dojutsu-user 
@Divy123 
sir this is working as well

**Comment by lav-joshi** [comment]
Screenshot from 2019-11-23 19-23-56
Screenshot from 2019-11-23 19-24-16

**Comment by dojutsu-user** [comment]
Please make another PR as the repository that submitted this pull request has been deleted.

**Pull request closed without merging**
