### PR TITLE
Login Page UI

### PR DESCRIPTION
**Pull request by arhum602**
Related: #4

### CODE REVIEW

**Comment by dojutsu-user** [comment]
Hi @arhum602 
Please add some description about this PR.
And also add a screenshot so that it is easier to review.

**Comment by dojutsu-user** [comment]
Please attach the screenshot in the PR description and not in the PR.

**Review by arhum602 — COMMENTED** [review]
Login

**Comment by rishabhshuklax** [comment]
Make separate PRs for #1 and #4  both from different branches, you have codes for both of them in the same PR.

**Pull request closed without merging**
