### PR TITLE
Weather app(Weather App (Web App, due date: 10 Nov.) )issue#3

### PR DESCRIPTION
**Pull request by blank-27**

### CODE REVIEW

**Comment by blank-27** [comment]
made the javascript working in codepen.io

**Comment by Divy123** [comment]
Where is the link to codepen?

**Comment by blank-27** [comment]
it is already there

**Comment by blank-27** [comment]
@Divy123  It's already there.
https://codepen.io/blank-27/pen/rNNKbGa

**Comment by blank-27** [comment]
@Divy123 added the codepen link

**Pull request merged**
